changes to check score

diff --git a/.github/workflows/workflowFile.yml b/.github/workflows/workflowFile.yml
--- a/.github/workflows/workflowFile.yml
+++ b/.github/workflows/workflowFile.yml
@@ -32,17 +32,20 @@ jobs:
       - name: Run Docker container
         run: docker run --rm alcinasharon21/mlops:latest
 
-      - name: Extract score from container output
-        id: extract-score
-        run: echo "::set-output name=score::$(docker run --rm alcinasharon21/mlops:latest | grep 'Score:' | awk '{print $2}')"
-  
-      - name: Check score
-        run: |
-          score=${{ steps.extract-score.outputs.score }}
-          if (( $(echo "$score > 0.3" | bc -l) )); then
-            echo "Score is greater than 0.30, test succeeded."
-          else
-            echo "Score is not greater than 0.30, test failed."
-            exit 1
-          fi
-  
+      - name: Check Score
+        # id: extract-score
+        # run: echo "::set-output name=score::$(docker run --rm alcinasharon21/mlops:latest | grep 'Score:' | awk '{print $2}')"
+        run:
+          OUTPUT=$(docker run --rm alcinasharon21/mlops:latest)
+          echo "Score:"
+          echo "$OUTPUT"
+          if [[ `echo "$OUTPUT 0.30" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
+      # - name: Check score
+      #   run: |
+      #     score=${{ steps.extract-score.outputs.score }}
+      #     if (( $(echo "$score > 0.3" | bc -l) )); then
+      #       echo "Score is greater than 0.30, test succeeded."
+      #     else
+      #       echo "Score is not greater than 0.30, test failed."
+      #       exit 1
+      #     fi
